/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CreateJobPayloadDTO {
  applicationQuestions: {
    enteredQuestions: string[];
    isApplicationSourceRequired: boolean;
    isCoverLetterRequired: boolean;
    isEmailRequired: boolean;
    isHomeAddressRequired: boolean;
    isNameRequired: boolean;
    isPhoneNumberRequired: boolean;
    isPortfolioLinkRequired: boolean;
    isResumeRequired: boolean;
  };
  department: string;
  enteredInterviewQuestions: string[];
  jobDescription: string;
  jobTitle: string;
  jobType: string;
  location: string;
  openings: number;
  salary: string;
  salaryRate: string;
  skills: any[];
  startDate: string;
}
