/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CreateCulturefyJobApplicationPayloadDTO {
  applicantName: string;
  coverLetter: string;
  email: string;
  jobId: string;
  location: {
    cityId: string;
    coordinates: any[];
    countryId: string;
    formattedAddress: string | null;
    stateId: string;
    street: string | null;
    type: 'Point' | null;
    zipcode: number | null;
  };
  phoneNumber: string;
  resume: string;
}

export interface GetDropdownJobApplicantsByJobIdParamsPayloadDTO {
  jobId: string;
}

export interface GetDropdownJobApplicantsByJobIdQueryPayloadDTO {
  applicantName?: string;
}
