/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AddRecruitmentInterviewDataPayloadDTO {
  hosts: string[];
  invitedCandidates: string[];
  jobId: string;
  urlCode: string;
}

export interface ToAndFromTimeDTOValidationSchemaPayloadDTO {
  fromTime: Date;
  toTime: Date;
}
